# Generated by Django 2.2.15 on 2020-08-29 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_id', models.IntegerField(auto_created=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'relation',
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.BooleanField(default=False)),
                ('send_message', models.BooleanField(default=True)),
                ('forward_message', models.BooleanField(default=True)),
                ('copy_message', models.BooleanField(default=True)),
                ('view_profile', models.BooleanField(default=True)),
                ('view_followers', models.BooleanField(default=True)),
                ('view_following', models.BooleanField(default=True)),
                ('view_posts', models.BooleanField(default=True)),
                ('commment_on_post', models.BooleanField(default=True)),
                ('like_on_post', models.BooleanField(default=True)),
                ('share_on_post', models.BooleanField(default=True)),
                ('close_friend', models.BooleanField(default=False)),
                ('secret_crush', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Connections',
            },
        ),
    ]
