version: '3'
networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
#    depends_on:
#      - cassandra

#  cassandra:
#    image: 'bitnami/cassandra:latest'
#    networks:
#      - app-tier
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    depends_on:
#      - cassandra
    networks:
      - app-tier

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
#      - cassandra
      - db