version: "3.3"
services:
  redis:
    image: redis:5.0.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  db:
    build: .
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration
      - collectstatics
      - redis
  migration:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
  collectstatics:
    build: .
    command: python manage.py collectstatic --noinput
    volumes:
      - .:/code