# Generated by Django 3.0.11 on 2020-12-30 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('height', models.IntegerField(default=800)),
                ('width', models.IntegerField(default=40)),
                ('ratio', models.FloatField(default=0.5)),
                ('url', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('can_comment', models.BooleanField(default=True)),
                ('can_share', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('can_bookmark', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('view_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.Post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('x_axis', models.FloatField(default=50)),
                ('y_axis', models.FloatField(default=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.Image')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.Post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('report_type', models.IntegerField()),
                ('note', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.Post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.Post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.Post'),
        ),
        migrations.AddField(
            model_name='image',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('comment', models.TextField(default='')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.Post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.Post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
