# Generated by Django 2.2.15 on 2020-09-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
    ]
