# Generated by Django 2.2.15 on 2020-09-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0015_auto_20200923_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='notification/2020-09-25'),
        ),
    ]
