# Generated by Django 2.2.15 on 2020-09-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_auto_20200906_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_message', models.CharField(max_length=100)),
                ('last_message_time', models.DateTimeField(auto_now=True)),
                ('unseen_message', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('froze', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient', to='accounts.UserDetails')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='accounts.UserDetails')),
            ],
        ),
    ]
