# Generated by Django 3.1 on 2020-12-31 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_message', models.CharField(max_length=100)),
                ('last_message_time', models.DateTimeField(auto_now=True)),
                ('unseen_message', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('froze', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient', to='accounts.userdetails')),
                ('sender', models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='accounts.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('sender_id', models.CharField(max_length=36)),
                ('recipient_id', models.CharField(max_length=36)),
                ('message', models.TextField(max_length=500)),
                ('message_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=0)),
                ('conversation_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.conversation')),
            ],
        ),
    ]
